###

GET http://localhost:3000/
Content-type: application/json

{}

###

GET http://localhost:3000/presensi
Content-type: application/json

{}

###

GET http://localhost:3000/presensi
Content-type: application/json

###

POST http://34.101.161.86:3000/presensi
Content-type: application/json

{
    "idRfid": "78285894"
}