###

GET http://localhost:3000/
Content-type: application/json

{}

###

GET http://localhost:5000/dosen
Content-type: application/json

{}

###

GET http://localhost:3001/presensi?name=
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzIyMzU0NDc2LCJleHAiOjE3MjQ5NDY0NzZ9.-5sk4Tt4vOIHBEZca9A4AAhMnHMXvfJDWSZfEeiagbU

###

POST http://localhost:3001/presensi
Content-type: application/json

{
    "idRfid": "OiqB1ZpN"
}

###

POST http://34.101.161.86:3000/presensi
Content-type: application/json

{
    "idRfid": "OiqB1ZpN"
}

###

POST http://34.101.161.86:3000/login
Content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}

###

POST http://34.101.161.86:3000/register
Content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}


###

GET http://34.101.161.86:3000/presensi
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzIyMzU0NDc2LCJleHAiOjE3MjQ5NDY0NzZ9.-5sk4Tt4vOIHBEZca9A4AAhMnHMXvfJDWSZfEeiagbU