###

GET http://localhost:3000/
Content-type: application/json

{}

###

GET http://localhost:3000/presensi
Content-type: application/json

{}

###

GET http://localhost:3000/presensi
Content-type: application/json

###

POST http://34.101.161.86:3000/presensi
Content-type: application/json

{
    "idRfid": "78285894"
}

###

POST http://34.101.161.86:3000/login
Content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}

###

POST http://34.101.161.86:3000/register
Content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}
